name: tests

on:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Run tests
        run: cargo test

      - name: Build release with all features
        run: cargo build --release --all-features

      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-build
          path: target/release/
